name: "hyperliquid"

services:
  validator:
    profiles: ["validator"]
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CHAIN=${CHAIN}
        - OVERRIDE_PEER_IPS=${OVERRIDE_PEER_IPS}
        - OVERRIDE_TRY_NEW_PEERS=${OVERRIDE_TRY_NEW_PEERS}
    ports:
      - "4000-4010:4000-4010"
    volumes:
      - hl-data:/home/hluser/hl/data

volumes:
  hl-data:
    driver: local
